// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: encoder/encoder.proto

package encoder

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Encoder:
	//
	//	*Encoder_SentenceTransformer_
	Encoder isEncoder_Encoder `protobuf_oneof:"encoder"`
}

func (x *Encoder) Reset() {
	*x = Encoder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_encoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encoder) ProtoMessage() {}

func (x *Encoder) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_encoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encoder.ProtoReflect.Descriptor instead.
func (*Encoder) Descriptor() ([]byte, []int) {
	return file_encoder_encoder_proto_rawDescGZIP(), []int{0}
}

func (m *Encoder) GetEncoder() isEncoder_Encoder {
	if m != nil {
		return m.Encoder
	}
	return nil
}

func (x *Encoder) GetSentenceTransformer() *Encoder_SentenceTransformer {
	if x, ok := x.GetEncoder().(*Encoder_SentenceTransformer_); ok {
		return x.SentenceTransformer
	}
	return nil
}

type isEncoder_Encoder interface {
	isEncoder_Encoder()
}

type Encoder_SentenceTransformer_ struct {
	SentenceTransformer *Encoder_SentenceTransformer `protobuf:"bytes,3,opt,name=sentence_transformer,json=sentenceTransformer,proto3,oneof"`
}

func (*Encoder_SentenceTransformer_) isEncoder_Encoder() {}

type Encoder_SentenceTransformer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Encoder_SentenceTransformer) Reset() {
	*x = Encoder_SentenceTransformer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_encoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encoder_SentenceTransformer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encoder_SentenceTransformer) ProtoMessage() {}

func (x *Encoder_SentenceTransformer) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_encoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encoder_SentenceTransformer.ProtoReflect.Descriptor instead.
func (*Encoder_SentenceTransformer) Descriptor() ([]byte, []int) {
	return file_encoder_encoder_proto_rawDescGZIP(), []int{0, 0}
}

var File_encoder_encoder_proto protoreflect.FileDescriptor

var file_encoder_encoder_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7e, 0x0a, 0x07, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x14, 0x73,
	0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x48, 0x00, 0x52, 0x13, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x6e, 0x63, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x1a, 0x15,
	0x0a, 0x13, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x42, 0x2e, 0x42, 0x0c, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x1c, 0x62, 0x69, 0x67, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x2e, 0x6f, 0x72, 0x2e,
	0x6b, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encoder_encoder_proto_rawDescOnce sync.Once
	file_encoder_encoder_proto_rawDescData = file_encoder_encoder_proto_rawDesc
)

func file_encoder_encoder_proto_rawDescGZIP() []byte {
	file_encoder_encoder_proto_rawDescOnce.Do(func() {
		file_encoder_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_encoder_encoder_proto_rawDescData)
	})
	return file_encoder_encoder_proto_rawDescData
}

var file_encoder_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_encoder_encoder_proto_goTypes = []any{
	(*Encoder)(nil),                     // 0: Encoder
	(*Encoder_SentenceTransformer)(nil), // 1: Encoder.SentenceTransformer
}
var file_encoder_encoder_proto_depIdxs = []int32{
	1, // 0: Encoder.sentence_transformer:type_name -> Encoder.SentenceTransformer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_encoder_encoder_proto_init() }
func file_encoder_encoder_proto_init() {
	if File_encoder_encoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encoder_encoder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Encoder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encoder_encoder_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Encoder_SentenceTransformer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_encoder_encoder_proto_msgTypes[0].OneofWrappers = []any{
		(*Encoder_SentenceTransformer_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encoder_encoder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encoder_encoder_proto_goTypes,
		DependencyIndexes: file_encoder_encoder_proto_depIdxs,
		MessageInfos:      file_encoder_encoder_proto_msgTypes,
	}.Build()
	File_encoder_encoder_proto = out.File
	file_encoder_encoder_proto_rawDesc = nil
	file_encoder_encoder_proto_goTypes = nil
	file_encoder_encoder_proto_depIdxs = nil
}
