// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: encoder/encoder.proto

package encoder

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Encoder with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Encoder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Encoder with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EncoderMultiError, or nil if none found.
func (m *Encoder) ValidateAll() error {
	return m.validate(true)
}

func (m *Encoder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Encoder.(type) {
	case *Encoder_SentenceTransformer_:
		if v == nil {
			err := EncoderValidationError{
				field:  "Encoder",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSentenceTransformer()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EncoderValidationError{
						field:  "SentenceTransformer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EncoderValidationError{
						field:  "SentenceTransformer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSentenceTransformer()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EncoderValidationError{
					field:  "SentenceTransformer",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return EncoderMultiError(errors)
	}

	return nil
}

// EncoderMultiError is an error wrapping multiple validation errors returned
// by Encoder.ValidateAll() if the designated constraints aren't met.
type EncoderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EncoderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EncoderMultiError) AllErrors() []error { return m }

// EncoderValidationError is the validation error returned by Encoder.Validate
// if the designated constraints aren't met.
type EncoderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EncoderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EncoderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EncoderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EncoderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EncoderValidationError) ErrorName() string { return "EncoderValidationError" }

// Error satisfies the builtin error interface
func (e EncoderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEncoder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EncoderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EncoderValidationError{}

// Validate checks the field values on Encoder_SentenceTransformer with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Encoder_SentenceTransformer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Encoder_SentenceTransformer with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Encoder_SentenceTransformerMultiError, or nil if none found.
func (m *Encoder_SentenceTransformer) ValidateAll() error {
	return m.validate(true)
}

func (m *Encoder_SentenceTransformer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return Encoder_SentenceTransformerMultiError(errors)
	}

	return nil
}

// Encoder_SentenceTransformerMultiError is an error wrapping multiple
// validation errors returned by Encoder_SentenceTransformer.ValidateAll() if
// the designated constraints aren't met.
type Encoder_SentenceTransformerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Encoder_SentenceTransformerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Encoder_SentenceTransformerMultiError) AllErrors() []error { return m }

// Encoder_SentenceTransformerValidationError is the validation error returned
// by Encoder_SentenceTransformer.Validate if the designated constraints
// aren't met.
type Encoder_SentenceTransformerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Encoder_SentenceTransformerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Encoder_SentenceTransformerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Encoder_SentenceTransformerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Encoder_SentenceTransformerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Encoder_SentenceTransformerValidationError) ErrorName() string {
	return "Encoder_SentenceTransformerValidationError"
}

// Error satisfies the builtin error interface
func (e Encoder_SentenceTransformerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEncoder_SentenceTransformer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Encoder_SentenceTransformerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Encoder_SentenceTransformerValidationError{}
