// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: searcher/service/opensearch.proto

package service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OSSearcherSearchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OSSearcherSearchRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OSSearcherSearchRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OSSearcherSearchRequestMultiError, or nil if none found.
func (m *OSSearcherSearchRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OSSearcherSearchRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Query

	// no validation rules for Exclude

	// no validation rules for Size

	for idx, item := range m.GetFilters() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OSSearcherSearchRequestValidationError{
						field:  fmt.Sprintf("Filters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OSSearcherSearchRequestValidationError{
						field:  fmt.Sprintf("Filters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OSSearcherSearchRequestValidationError{
					field:  fmt.Sprintf("Filters[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OSSearcherSearchRequestMultiError(errors)
	}

	return nil
}

// OSSearcherSearchRequestMultiError is an error wrapping multiple validation
// errors returned by OSSearcherSearchRequest.ValidateAll() if the designated
// constraints aren't met.
type OSSearcherSearchRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OSSearcherSearchRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OSSearcherSearchRequestMultiError) AllErrors() []error { return m }

// OSSearcherSearchRequestValidationError is the validation error returned by
// OSSearcherSearchRequest.Validate if the designated constraints aren't met.
type OSSearcherSearchRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OSSearcherSearchRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OSSearcherSearchRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OSSearcherSearchRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OSSearcherSearchRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OSSearcherSearchRequestValidationError) ErrorName() string {
	return "OSSearcherSearchRequestValidationError"
}

// Error satisfies the builtin error interface
func (e OSSearcherSearchRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOSSearcherSearchRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OSSearcherSearchRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OSSearcherSearchRequestValidationError{}

// Validate checks the field values on OSSearcherSearchResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OSSearcherSearchResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OSSearcherSearchResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OSSearcherSearchResponseMultiError, or nil if none found.
func (m *OSSearcherSearchResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OSSearcherSearchResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OSSearcherSearchResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OSSearcherSearchResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OSSearcherSearchResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OSSearcherSearchResponseMultiError(errors)
	}

	return nil
}

// OSSearcherSearchResponseMultiError is an error wrapping multiple validation
// errors returned by OSSearcherSearchResponse.ValidateAll() if the designated
// constraints aren't met.
type OSSearcherSearchResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OSSearcherSearchResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OSSearcherSearchResponseMultiError) AllErrors() []error { return m }

// OSSearcherSearchResponseValidationError is the validation error returned by
// OSSearcherSearchResponse.Validate if the designated constraints aren't met.
type OSSearcherSearchResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OSSearcherSearchResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OSSearcherSearchResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OSSearcherSearchResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OSSearcherSearchResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OSSearcherSearchResponseValidationError) ErrorName() string {
	return "OSSearcherSearchResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OSSearcherSearchResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOSSearcherSearchResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OSSearcherSearchResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OSSearcherSearchResponseValidationError{}
