// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: searcher/service/opensearch.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OSSearcherService_Search_FullMethodName = "/OSSearcherService/Search"
)

// OSSearcherServiceClient is the client API for OSSearcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSSearcherServiceClient interface {
	Search(ctx context.Context, in *OSSearcherSearchRequest, opts ...grpc.CallOption) (*OSSearcherSearchResponse, error)
}

type oSSearcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOSSearcherServiceClient(cc grpc.ClientConnInterface) OSSearcherServiceClient {
	return &oSSearcherServiceClient{cc}
}

func (c *oSSearcherServiceClient) Search(ctx context.Context, in *OSSearcherSearchRequest, opts ...grpc.CallOption) (*OSSearcherSearchResponse, error) {
	out := new(OSSearcherSearchResponse)
	err := c.cc.Invoke(ctx, OSSearcherService_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSSearcherServiceServer is the server API for OSSearcherService service.
// All implementations must embed UnimplementedOSSearcherServiceServer
// for forward compatibility
type OSSearcherServiceServer interface {
	Search(context.Context, *OSSearcherSearchRequest) (*OSSearcherSearchResponse, error)
	mustEmbedUnimplementedOSSearcherServiceServer()
}

// UnimplementedOSSearcherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOSSearcherServiceServer struct {
}

func (UnimplementedOSSearcherServiceServer) Search(context.Context, *OSSearcherSearchRequest) (*OSSearcherSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedOSSearcherServiceServer) mustEmbedUnimplementedOSSearcherServiceServer() {}

// UnsafeOSSearcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSSearcherServiceServer will
// result in compilation errors.
type UnsafeOSSearcherServiceServer interface {
	mustEmbedUnimplementedOSSearcherServiceServer()
}

func RegisterOSSearcherServiceServer(s grpc.ServiceRegistrar, srv OSSearcherServiceServer) {
	s.RegisterService(&OSSearcherService_ServiceDesc, srv)
}

func _OSSearcherService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OSSearcherSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSearcherServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSSearcherService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSearcherServiceServer).Search(ctx, req.(*OSSearcherSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OSSearcherService_ServiceDesc is the grpc.ServiceDesc for OSSearcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSSearcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OSSearcherService",
	HandlerType: (*OSSearcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _OSSearcherService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searcher/service/opensearch.proto",
}
