# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: searcher/service/opensearch.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'searcher/service/opensearch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_pb2 as item__pb2
import search_pb2 as search__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!searcher/service/opensearch.proto\x1a\nitem.proto\x1a\x0csearch.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf5\x01\n\x17OSSearcherSearchRequest\x12\x39\n\x05query\x18\x01 \x03(\x0b\x32#.OSSearcherSearchRequest.QueryEntryR\x05query\x12\x18\n\x07\x65xclude\x18\x02 \x01(\tR\x07\x65xclude\x12\x12\n\x04size\x18\x03 \x01(\x05R\x04size\x12\x31\n\x07\x66ilters\x18\x05 \x03(\x0b\x32\x17.google.protobuf.StructR\x07\x66ilters\x1a\x38\n\nQueryEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01J\x04\x08\x04\x10\x05\"7\n\x18OSSearcherSearchResponse\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x05.ItemR\x05items2T\n\x11OSSearcherService\x12?\n\x06Search\x12\x18.OSSearcherSearchRequest\x1a\x19.OSSearcherSearchResponse\"\x00\x42:B\x0fOpensearchProtoP\x01Z%bigkinds.or.kr/proto/searcher/serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searcher.service.opensearch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\017OpensearchProtoP\001Z%bigkinds.or.kr/proto/searcher/service'
  _globals['_OSSEARCHERSEARCHREQUEST_QUERYENTRY']._loaded_options = None
  _globals['_OSSEARCHERSEARCHREQUEST_QUERYENTRY']._serialized_options = b'8\001'
  _globals['_OSSEARCHERSEARCHREQUEST']._serialized_start=94
  _globals['_OSSEARCHERSEARCHREQUEST']._serialized_end=339
  _globals['_OSSEARCHERSEARCHREQUEST_QUERYENTRY']._serialized_start=277
  _globals['_OSSEARCHERSEARCHREQUEST_QUERYENTRY']._serialized_end=333
  _globals['_OSSEARCHERSEARCHRESPONSE']._serialized_start=341
  _globals['_OSSEARCHERSEARCHRESPONSE']._serialized_end=396
  _globals['_OSSEARCHERSERVICE']._serialized_start=398
  _globals['_OSSEARCHERSERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
