# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from searcher.service import opensearch_pb2 as searcher_dot_service_dot_opensearch__pb2


class OSSearcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/OSSearcherService/Search',
                request_serializer=searcher_dot_service_dot_opensearch__pb2.OSSearcherSearchRequest.SerializeToString,
                response_deserializer=searcher_dot_service_dot_opensearch__pb2.OSSearcherSearchResponse.FromString,
                )


class OSSearcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OSSearcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=searcher_dot_service_dot_opensearch__pb2.OSSearcherSearchRequest.FromString,
                    response_serializer=searcher_dot_service_dot_opensearch__pb2.OSSearcherSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OSSearcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OSSearcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OSSearcherService/Search',
            searcher_dot_service_dot_opensearch__pb2.OSSearcherSearchRequest.SerializeToString,
            searcher_dot_service_dot_opensearch__pb2.OSSearcherSearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
