// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: searcher/searcher.proto

package searcher

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearcherConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Searcher:
	//
	//	*SearcherConfig_Opensearch
	Searcher isSearcherConfig_Searcher `protobuf_oneof:"searcher"`
}

func (x *SearcherConfig) Reset() {
	*x = SearcherConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searcher_searcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearcherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearcherConfig) ProtoMessage() {}

func (x *SearcherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_searcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearcherConfig.ProtoReflect.Descriptor instead.
func (*SearcherConfig) Descriptor() ([]byte, []int) {
	return file_searcher_searcher_proto_rawDescGZIP(), []int{0}
}

func (m *SearcherConfig) GetSearcher() isSearcherConfig_Searcher {
	if m != nil {
		return m.Searcher
	}
	return nil
}

func (x *SearcherConfig) GetOpensearch() *OpenSearchSearcher {
	if x, ok := x.GetSearcher().(*SearcherConfig_Opensearch); ok {
		return x.Opensearch
	}
	return nil
}

type isSearcherConfig_Searcher interface {
	isSearcherConfig_Searcher()
}

type SearcherConfig_Opensearch struct {
	Opensearch *OpenSearchSearcher `protobuf:"bytes,2,opt,name=opensearch,proto3,oneof"`
}

func (*SearcherConfig_Opensearch) isSearcherConfig_Searcher() {}

type SearcherConfigWithID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SearcherConfig *SearcherConfig `protobuf:"bytes,2,opt,name=searcher_config,json=searcherConfig,proto3" json:"searcher_config,omitempty"`
}

func (x *SearcherConfigWithID) Reset() {
	*x = SearcherConfigWithID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searcher_searcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearcherConfigWithID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearcherConfigWithID) ProtoMessage() {}

func (x *SearcherConfigWithID) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_searcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearcherConfigWithID.ProtoReflect.Descriptor instead.
func (*SearcherConfigWithID) Descriptor() ([]byte, []int) {
	return file_searcher_searcher_proto_rawDescGZIP(), []int{1}
}

func (x *SearcherConfigWithID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearcherConfigWithID) GetSearcherConfig() *SearcherConfig {
	if x != nil {
		return x.SearcherConfig
	}
	return nil
}

var File_searcher_searcher_proto protoreflect.FileDescriptor

var file_searcher_searcher_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a,
	0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x35, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x6e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x0a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x65, 0x72, 0x22, 0x60, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x57, 0x69, 0x74, 0x68, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x0e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x42, 0x30, 0x42, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1d, 0x62, 0x69, 0x67, 0x6b, 0x69, 0x6e, 0x64,
	0x73, 0x2e, 0x6f, 0x72, 0x2e, 0x6b, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_searcher_searcher_proto_rawDescOnce sync.Once
	file_searcher_searcher_proto_rawDescData = file_searcher_searcher_proto_rawDesc
)

func file_searcher_searcher_proto_rawDescGZIP() []byte {
	file_searcher_searcher_proto_rawDescOnce.Do(func() {
		file_searcher_searcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_searcher_searcher_proto_rawDescData)
	})
	return file_searcher_searcher_proto_rawDescData
}

var file_searcher_searcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_searcher_searcher_proto_goTypes = []any{
	(*SearcherConfig)(nil),       // 0: SearcherConfig
	(*SearcherConfigWithID)(nil), // 1: SearcherConfigWithID
	(*OpenSearchSearcher)(nil),   // 2: OpenSearchSearcher
}
var file_searcher_searcher_proto_depIdxs = []int32{
	2, // 0: SearcherConfig.opensearch:type_name -> OpenSearchSearcher
	0, // 1: SearcherConfigWithID.searcher_config:type_name -> SearcherConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_searcher_searcher_proto_init() }
func file_searcher_searcher_proto_init() {
	if File_searcher_searcher_proto != nil {
		return
	}
	file_searcher_opensearch_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_searcher_searcher_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearcherConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searcher_searcher_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearcherConfigWithID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_searcher_searcher_proto_msgTypes[0].OneofWrappers = []any{
		(*SearcherConfig_Opensearch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_searcher_searcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_searcher_searcher_proto_goTypes,
		DependencyIndexes: file_searcher_searcher_proto_depIdxs,
		MessageInfos:      file_searcher_searcher_proto_msgTypes,
	}.Build()
	File_searcher_searcher_proto = out.File
	file_searcher_searcher_proto_rawDesc = nil
	file_searcher_searcher_proto_goTypes = nil
	file_searcher_searcher_proto_depIdxs = nil
}
