# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: searcher/searcher.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'searcher/searcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from searcher import opensearch_pb2 as searcher_dot_opensearch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17searcher/searcher.proto\x1a\x17validate/validate.proto\x1a\x19searcher/opensearch.proto\"S\n\x0eSearcherConfig\x12\x35\n\nopensearch\x18\x02 \x01(\x0b\x32\x13.OpenSearchSearcherH\x00R\nopensearchB\n\n\x08searcher\"`\n\x14SearcherConfigWithID\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x38\n\x0fsearcher_config\x18\x02 \x01(\x0b\x32\x0f.SearcherConfigR\x0esearcherConfigB0B\rSearcherProtoP\x01Z\x1d\x62igkinds.or.kr/proto/searcherb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searcher.searcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\rSearcherProtoP\001Z\035bigkinds.or.kr/proto/searcher'
  _globals['_SEARCHERCONFIG']._serialized_start=79
  _globals['_SEARCHERCONFIG']._serialized_end=162
  _globals['_SEARCHERCONFIGWITHID']._serialized_start=164
  _globals['_SEARCHERCONFIGWITHID']._serialized_end=260
# @@protoc_insertion_point(module_scope)
