// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: searcher/searcher_resource.proto

package searcher

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearcherResourceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Backend:
	//
	//	*SearcherResourceConfig_Cluster_
	Backend isSearcherResourceConfig_Backend `protobuf_oneof:"backend"`
}

func (x *SearcherResourceConfig) Reset() {
	*x = SearcherResourceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searcher_searcher_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearcherResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearcherResourceConfig) ProtoMessage() {}

func (x *SearcherResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_searcher_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearcherResourceConfig.ProtoReflect.Descriptor instead.
func (*SearcherResourceConfig) Descriptor() ([]byte, []int) {
	return file_searcher_searcher_resource_proto_rawDescGZIP(), []int{0}
}

func (m *SearcherResourceConfig) GetBackend() isSearcherResourceConfig_Backend {
	if m != nil {
		return m.Backend
	}
	return nil
}

func (x *SearcherResourceConfig) GetCluster() *SearcherResourceConfig_Cluster {
	if x, ok := x.GetBackend().(*SearcherResourceConfig_Cluster_); ok {
		return x.Cluster
	}
	return nil
}

type isSearcherResourceConfig_Backend interface {
	isSearcherResourceConfig_Backend()
}

type SearcherResourceConfig_Cluster_ struct {
	Cluster *SearcherResourceConfig_Cluster `protobuf:"bytes,1,opt,name=cluster,proto3,oneof"`
}

func (*SearcherResourceConfig_Cluster_) isSearcherResourceConfig_Backend() {}

type SearcherResourceConfig_ContainerResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    string `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory string `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu    string `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *SearcherResourceConfig_ContainerResource) Reset() {
	*x = SearcherResourceConfig_ContainerResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searcher_searcher_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearcherResourceConfig_ContainerResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearcherResourceConfig_ContainerResource) ProtoMessage() {}

func (x *SearcherResourceConfig_ContainerResource) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_searcher_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearcherResourceConfig_ContainerResource.ProtoReflect.Descriptor instead.
func (*SearcherResourceConfig_ContainerResource) Descriptor() ([]byte, []int) {
	return file_searcher_searcher_resource_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SearcherResourceConfig_ContainerResource) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *SearcherResourceConfig_ContainerResource) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *SearcherResourceConfig_ContainerResource) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

type SearcherResourceConfig_Cluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context  string                                    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Device   string                                    `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Requests *SearcherResourceConfig_ContainerResource `protobuf:"bytes,3,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits   *SearcherResourceConfig_ContainerResource `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *SearcherResourceConfig_Cluster) Reset() {
	*x = SearcherResourceConfig_Cluster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searcher_searcher_resource_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearcherResourceConfig_Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearcherResourceConfig_Cluster) ProtoMessage() {}

func (x *SearcherResourceConfig_Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_searcher_resource_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearcherResourceConfig_Cluster.ProtoReflect.Descriptor instead.
func (*SearcherResourceConfig_Cluster) Descriptor() ([]byte, []int) {
	return file_searcher_searcher_resource_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SearcherResourceConfig_Cluster) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SearcherResourceConfig_Cluster) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SearcherResourceConfig_Cluster) GetRequests() *SearcherResourceConfig_ContainerResource {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *SearcherResourceConfig_Cluster) GetLimits() *SearcherResourceConfig_ContainerResource {
	if x != nil {
		return x.Limits
	}
	return nil
}

var File_searcher_searcher_resource_proto protoreflect.FileDescriptor

var file_searcher_searcher_resource_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x03, 0x0a, 0x16,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3b, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x1a, 0x61, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x12, 0x1f, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x67, 0x70, 0x75, 0x1a, 0xf1, 0x01, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x19, 0xfa, 0x42, 0x16, 0x72, 0x14, 0x52, 0x08, 0x67, 0x61, 0x6e, 0x67,
	0x6e, 0x61, 0x6d, 0x31, 0x52, 0x08, 0x67, 0x61, 0x6e, 0x67, 0x6e, 0x61, 0x6d, 0x32, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0f, 0xfa, 0x42, 0x0c, 0x72, 0x0a, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x52, 0x03, 0x61, 0x31, 0x30, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x45, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x42, 0x38, 0x42, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x1d, 0x62, 0x69, 0x67, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x2e, 0x6f, 0x72, 0x2e, 0x6b, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_searcher_searcher_resource_proto_rawDescOnce sync.Once
	file_searcher_searcher_resource_proto_rawDescData = file_searcher_searcher_resource_proto_rawDesc
)

func file_searcher_searcher_resource_proto_rawDescGZIP() []byte {
	file_searcher_searcher_resource_proto_rawDescOnce.Do(func() {
		file_searcher_searcher_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_searcher_searcher_resource_proto_rawDescData)
	})
	return file_searcher_searcher_resource_proto_rawDescData
}

var file_searcher_searcher_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_searcher_searcher_resource_proto_goTypes = []any{
	(*SearcherResourceConfig)(nil),                   // 0: SearcherResourceConfig
	(*SearcherResourceConfig_ContainerResource)(nil), // 1: SearcherResourceConfig.ContainerResource
	(*SearcherResourceConfig_Cluster)(nil),           // 2: SearcherResourceConfig.Cluster
}
var file_searcher_searcher_resource_proto_depIdxs = []int32{
	2, // 0: SearcherResourceConfig.cluster:type_name -> SearcherResourceConfig.Cluster
	1, // 1: SearcherResourceConfig.Cluster.requests:type_name -> SearcherResourceConfig.ContainerResource
	1, // 2: SearcherResourceConfig.Cluster.limits:type_name -> SearcherResourceConfig.ContainerResource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_searcher_searcher_resource_proto_init() }
func file_searcher_searcher_resource_proto_init() {
	if File_searcher_searcher_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_searcher_searcher_resource_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearcherResourceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searcher_searcher_resource_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearcherResourceConfig_ContainerResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searcher_searcher_resource_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SearcherResourceConfig_Cluster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_searcher_searcher_resource_proto_msgTypes[0].OneofWrappers = []any{
		(*SearcherResourceConfig_Cluster_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_searcher_searcher_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_searcher_searcher_resource_proto_goTypes,
		DependencyIndexes: file_searcher_searcher_resource_proto_depIdxs,
		MessageInfos:      file_searcher_searcher_resource_proto_msgTypes,
	}.Build()
	File_searcher_searcher_resource_proto = out.File
	file_searcher_searcher_resource_proto_rawDesc = nil
	file_searcher_searcher_resource_proto_goTypes = nil
	file_searcher_searcher_resource_proto_depIdxs = nil
}
