# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: searcher/searcher_resource.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'searcher/searcher_resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n searcher/searcher_resource.proto\x1a\x17validate/validate.proto\"\xb7\x03\n\x16SearcherResourceConfig\x12;\n\x07\x63luster\x18\x01 \x01(\x0b\x32\x1f.SearcherResourceConfig.ClusterH\x00R\x07\x63luster\x1a\x61\n\x11\x43ontainerResource\x12\x19\n\x03\x63pu\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x03\x63pu\x12\x1f\n\x06memory\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x06memory\x12\x10\n\x03gpu\x18\x03 \x01(\tR\x03gpu\x1a\xf1\x01\n\x07\x43luster\x12\x33\n\x07\x63ontext\x18\x01 \x01(\tB\x19\xfa\x42\x16r\x14R\x08gangnam1R\x08gangnam2R\x07\x63ontext\x12\'\n\x06\x64\x65vice\x18\x02 \x01(\tB\x0f\xfa\x42\x0cr\nR\x03\x63puR\x03\x61\x31\x30R\x06\x64\x65vice\x12\x45\n\x08requests\x18\x03 \x01(\x0b\x32).SearcherResourceConfig.ContainerResourceR\x08requests\x12\x41\n\x06limits\x18\x04 \x01(\x0b\x32).SearcherResourceConfig.ContainerResourceR\x06limitsB\t\n\x07\x62\x61\x63kendB8B\x15SearcherResourceProtoP\x01Z\x1d\x62igkinds.or.kr/proto/searcherb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searcher.searcher_resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\025SearcherResourceProtoP\001Z\035bigkinds.or.kr/proto/searcher'
  _globals['_SEARCHERRESOURCECONFIG_CONTAINERRESOURCE'].fields_by_name['cpu']._loaded_options = None
  _globals['_SEARCHERRESOURCECONFIG_CONTAINERRESOURCE'].fields_by_name['cpu']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_SEARCHERRESOURCECONFIG_CONTAINERRESOURCE'].fields_by_name['memory']._loaded_options = None
  _globals['_SEARCHERRESOURCECONFIG_CONTAINERRESOURCE'].fields_by_name['memory']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_SEARCHERRESOURCECONFIG_CLUSTER'].fields_by_name['context']._loaded_options = None
  _globals['_SEARCHERRESOURCECONFIG_CLUSTER'].fields_by_name['context']._serialized_options = b'\372B\026r\024R\010gangnam1R\010gangnam2'
  _globals['_SEARCHERRESOURCECONFIG_CLUSTER'].fields_by_name['device']._loaded_options = None
  _globals['_SEARCHERRESOURCECONFIG_CLUSTER'].fields_by_name['device']._serialized_options = b'\372B\014r\nR\003cpuR\003a10'
  _globals['_SEARCHERRESOURCECONFIG']._serialized_start=62
  _globals['_SEARCHERRESOURCECONFIG']._serialized_end=501
  _globals['_SEARCHERRESOURCECONFIG_CONTAINERRESOURCE']._serialized_start=149
  _globals['_SEARCHERRESOURCECONFIG_CONTAINERRESOURCE']._serialized_end=246
  _globals['_SEARCHERRESOURCECONFIG_CLUSTER']._serialized_start=249
  _globals['_SEARCHERRESOURCECONFIG_CLUSTER']._serialized_end=490
# @@protoc_insertion_point(module_scope)
