// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: searcher/searcher.proto

package searcher

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearcherConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SearcherConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearcherConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SearcherConfigMultiError,
// or nil if none found.
func (m *SearcherConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *SearcherConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Searcher.(type) {
	case *SearcherConfig_Opensearch:
		if v == nil {
			err := SearcherConfigValidationError{
				field:  "Searcher",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetOpensearch()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearcherConfigValidationError{
						field:  "Opensearch",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearcherConfigValidationError{
						field:  "Opensearch",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetOpensearch()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearcherConfigValidationError{
					field:  "Opensearch",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return SearcherConfigMultiError(errors)
	}

	return nil
}

// SearcherConfigMultiError is an error wrapping multiple validation errors
// returned by SearcherConfig.ValidateAll() if the designated constraints
// aren't met.
type SearcherConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearcherConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearcherConfigMultiError) AllErrors() []error { return m }

// SearcherConfigValidationError is the validation error returned by
// SearcherConfig.Validate if the designated constraints aren't met.
type SearcherConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearcherConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearcherConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearcherConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearcherConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearcherConfigValidationError) ErrorName() string { return "SearcherConfigValidationError" }

// Error satisfies the builtin error interface
func (e SearcherConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearcherConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearcherConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearcherConfigValidationError{}

// Validate checks the field values on SearcherConfigWithID with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearcherConfigWithID) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearcherConfigWithID with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearcherConfigWithIDMultiError, or nil if none found.
func (m *SearcherConfigWithID) ValidateAll() error {
	return m.validate(true)
}

func (m *SearcherConfigWithID) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetSearcherConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SearcherConfigWithIDValidationError{
					field:  "SearcherConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SearcherConfigWithIDValidationError{
					field:  "SearcherConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSearcherConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SearcherConfigWithIDValidationError{
				field:  "SearcherConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SearcherConfigWithIDMultiError(errors)
	}

	return nil
}

// SearcherConfigWithIDMultiError is an error wrapping multiple validation
// errors returned by SearcherConfigWithID.ValidateAll() if the designated
// constraints aren't met.
type SearcherConfigWithIDMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearcherConfigWithIDMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearcherConfigWithIDMultiError) AllErrors() []error { return m }

// SearcherConfigWithIDValidationError is the validation error returned by
// SearcherConfigWithID.Validate if the designated constraints aren't met.
type SearcherConfigWithIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearcherConfigWithIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearcherConfigWithIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearcherConfigWithIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearcherConfigWithIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearcherConfigWithIDValidationError) ErrorName() string {
	return "SearcherConfigWithIDValidationError"
}

// Error satisfies the builtin error interface
func (e SearcherConfigWithIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearcherConfigWithID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearcherConfigWithIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearcherConfigWithIDValidationError{}
