# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: item.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x1a\x1cgoogle/protobuf/struct.proto\"e\n\x04Item\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x37\n\nattributes\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\nattributes\x12\x14\n\x05score\x18\x03 \x01(\x02R\x05score\"4\n\x05Items\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\x05items\x18\x02 \x03(\x0b\x32\x05.ItemR\x05itemsB#B\tItemProtoP\x01Z\x14\x62igkinds.or.kr/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\tItemProtoP\001Z\024bigkinds.or.kr/proto'
  _globals['_ITEM']._serialized_start=44
  _globals['_ITEM']._serialized_end=145
  _globals['_ITEMS']._serialized_start=147
  _globals['_ITEMS']._serialized_end=199
# @@protoc_insertion_point(module_scope)
