// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: search_config.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearcherType string    `protobuf:"bytes,3,opt,name=searcher_type,json=searcherType,proto3" json:"searcher_type,omitempty"`
	Reranker     *Reranker `protobuf:"bytes,4,opt,name=reranker,proto3" json:"reranker,omitempty"`
	UseGroup     bool      `protobuf:"varint,5,opt,name=use_group,json=useGroup,proto3" json:"use_group,omitempty"`
}

func (x *SearchConfig) Reset() {
	*x = SearchConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConfig) ProtoMessage() {}

func (x *SearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_search_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConfig.ProtoReflect.Descriptor instead.
func (*SearchConfig) Descriptor() ([]byte, []int) {
	return file_search_config_proto_rawDescGZIP(), []int{0}
}

func (x *SearchConfig) GetSearcherType() string {
	if x != nil {
		return x.SearcherType
	}
	return ""
}

func (x *SearchConfig) GetReranker() *Reranker {
	if x != nil {
		return x.Reranker
	}
	return nil
}

func (x *SearchConfig) GetUseGroup() bool {
	if x != nil {
		return x.UseGroup
	}
	return false
}

type Reranker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassageFields []string              `protobuf:"bytes,2,rep,name=passage_fields,json=passageFields,proto3" json:"passage_fields,omitempty"`
	RerankerType  string                `protobuf:"bytes,3,opt,name=reranker_type,json=rerankerType,proto3" json:"reranker_type,omitempty"`
	QuerySource   *Reranker_QuerySource `protobuf:"bytes,4,opt,name=query_source,json=querySource,proto3" json:"query_source,omitempty"`
	DedupField    string                `protobuf:"bytes,5,opt,name=dedup_field,json=dedupField,proto3" json:"dedup_field,omitempty"`
}

func (x *Reranker) Reset() {
	*x = Reranker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reranker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reranker) ProtoMessage() {}

func (x *Reranker) ProtoReflect() protoreflect.Message {
	mi := &file_search_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reranker.ProtoReflect.Descriptor instead.
func (*Reranker) Descriptor() ([]byte, []int) {
	return file_search_config_proto_rawDescGZIP(), []int{1}
}

func (x *Reranker) GetPassageFields() []string {
	if x != nil {
		return x.PassageFields
	}
	return nil
}

func (x *Reranker) GetRerankerType() string {
	if x != nil {
		return x.RerankerType
	}
	return ""
}

func (x *Reranker) GetQuerySource() *Reranker_QuerySource {
	if x != nil {
		return x.QuerySource
	}
	return nil
}

func (x *Reranker) GetDedupField() string {
	if x != nil {
		return x.DedupField
	}
	return ""
}

type Reranker_QuerySource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Source:
	//
	//	*Reranker_QuerySource_RawQuery_
	//	*Reranker_QuerySource_Query_
	//	*Reranker_QuerySource_ConcatQueryAndRawQuery_
	Source isReranker_QuerySource_Source `protobuf_oneof:"source"`
}

func (x *Reranker_QuerySource) Reset() {
	*x = Reranker_QuerySource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reranker_QuerySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reranker_QuerySource) ProtoMessage() {}

func (x *Reranker_QuerySource) ProtoReflect() protoreflect.Message {
	mi := &file_search_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reranker_QuerySource.ProtoReflect.Descriptor instead.
func (*Reranker_QuerySource) Descriptor() ([]byte, []int) {
	return file_search_config_proto_rawDescGZIP(), []int{1, 0}
}

func (m *Reranker_QuerySource) GetSource() isReranker_QuerySource_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *Reranker_QuerySource) GetRawQuery() *Reranker_QuerySource_RawQuery {
	if x, ok := x.GetSource().(*Reranker_QuerySource_RawQuery_); ok {
		return x.RawQuery
	}
	return nil
}

func (x *Reranker_QuerySource) GetQuery() *Reranker_QuerySource_Query {
	if x, ok := x.GetSource().(*Reranker_QuerySource_Query_); ok {
		return x.Query
	}
	return nil
}

func (x *Reranker_QuerySource) GetConcatQueryAndRawQuery() *Reranker_QuerySource_ConcatQueryAndRawQuery {
	if x, ok := x.GetSource().(*Reranker_QuerySource_ConcatQueryAndRawQuery_); ok {
		return x.ConcatQueryAndRawQuery
	}
	return nil
}

type isReranker_QuerySource_Source interface {
	isReranker_QuerySource_Source()
}

type Reranker_QuerySource_RawQuery_ struct {
	RawQuery *Reranker_QuerySource_RawQuery `protobuf:"bytes,1,opt,name=raw_query,json=rawQuery,proto3,oneof"`
}

type Reranker_QuerySource_Query_ struct {
	Query *Reranker_QuerySource_Query `protobuf:"bytes,2,opt,name=query,proto3,oneof"`
}

type Reranker_QuerySource_ConcatQueryAndRawQuery_ struct {
	ConcatQueryAndRawQuery *Reranker_QuerySource_ConcatQueryAndRawQuery `protobuf:"bytes,3,opt,name=concat_query_and_raw_query,json=concatQueryAndRawQuery,proto3,oneof"`
}

func (*Reranker_QuerySource_RawQuery_) isReranker_QuerySource_Source() {}

func (*Reranker_QuerySource_Query_) isReranker_QuerySource_Source() {}

func (*Reranker_QuerySource_ConcatQueryAndRawQuery_) isReranker_QuerySource_Source() {}

type Reranker_QuerySource_Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *Reranker_QuerySource_Query) Reset() {
	*x = Reranker_QuerySource_Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reranker_QuerySource_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reranker_QuerySource_Query) ProtoMessage() {}

func (x *Reranker_QuerySource_Query) ProtoReflect() protoreflect.Message {
	mi := &file_search_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reranker_QuerySource_Query.ProtoReflect.Descriptor instead.
func (*Reranker_QuerySource_Query) Descriptor() ([]byte, []int) {
	return file_search_config_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Reranker_QuerySource_Query) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type Reranker_QuerySource_RawQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Reranker_QuerySource_RawQuery) Reset() {
	*x = Reranker_QuerySource_RawQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reranker_QuerySource_RawQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reranker_QuerySource_RawQuery) ProtoMessage() {}

func (x *Reranker_QuerySource_RawQuery) ProtoReflect() protoreflect.Message {
	mi := &file_search_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reranker_QuerySource_RawQuery.ProtoReflect.Descriptor instead.
func (*Reranker_QuerySource_RawQuery) Descriptor() ([]byte, []int) {
	return file_search_config_proto_rawDescGZIP(), []int{1, 0, 1}
}

type Reranker_QuerySource_ConcatQueryAndRawQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *Reranker_QuerySource_ConcatQueryAndRawQuery) Reset() {
	*x = Reranker_QuerySource_ConcatQueryAndRawQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reranker_QuerySource_ConcatQueryAndRawQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reranker_QuerySource_ConcatQueryAndRawQuery) ProtoMessage() {}

func (x *Reranker_QuerySource_ConcatQueryAndRawQuery) ProtoReflect() protoreflect.Message {
	mi := &file_search_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reranker_QuerySource_ConcatQueryAndRawQuery.ProtoReflect.Descriptor instead.
func (*Reranker_QuerySource_ConcatQueryAndRawQuery) Descriptor() ([]byte, []int) {
	return file_search_config_proto_rawDescGZIP(), []int{1, 0, 2}
}

func (x *Reranker_QuerySource_ConcatQueryAndRawQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var File_search_config_proto protoreflect.FileDescriptor

var file_search_config_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93,
	0x01, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x3f, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1a, 0xfa, 0x42, 0x17, 0x72, 0x15, 0x52, 0x07, 0x63,
	0x6f, 0x6c, 0x62, 0x65, 0x72, 0x74, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x52, 0x08, 0x72,
	0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x75, 0x73, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x22, 0x97, 0x04, 0x0a, 0x08, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65,
	0x72, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x72, 0x61,
	0x6e, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x52, 0x02, 0x65, 0x35, 0x52, 0x0c, 0x72, 0x65, 0x72, 0x61,
	0x6e, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x64, 0x75, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x64, 0x75, 0x70, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x1a, 0xd2, 0x02, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x72, 0x61, 0x77, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65,
	0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x61,
	0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x08, 0x72, 0x61, 0x77, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x52, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x6a, 0x0a, 0x1a, 0x63, 0x6f, 0x6e, 0x63, 0x61,
	0x74, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x61, 0x77, 0x5f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x52, 0x65,
	0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6e,
	0x64, 0x52, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x16, 0x63, 0x6f, 0x6e,
	0x63, 0x61, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6e, 0x64, 0x52, 0x61, 0x77, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x1d, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x2e,
	0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6e, 0x64,
	0x52, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x08,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x42, 0x2b,
	0x42, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x14, 0x62, 0x69, 0x67, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x2e,
	0x6f, 0x72, 0x2e, 0x6b, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_search_config_proto_rawDescOnce sync.Once
	file_search_config_proto_rawDescData = file_search_config_proto_rawDesc
)

func file_search_config_proto_rawDescGZIP() []byte {
	file_search_config_proto_rawDescOnce.Do(func() {
		file_search_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_config_proto_rawDescData)
	})
	return file_search_config_proto_rawDescData
}

var file_search_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_config_proto_goTypes = []any{
	(*SearchConfig)(nil),                                // 0: SearchConfig
	(*Reranker)(nil),                                    // 1: Reranker
	(*Reranker_QuerySource)(nil),                        // 2: Reranker.QuerySource
	(*Reranker_QuerySource_Query)(nil),                  // 3: Reranker.QuerySource.Query
	(*Reranker_QuerySource_RawQuery)(nil),               // 4: Reranker.QuerySource.RawQuery
	(*Reranker_QuerySource_ConcatQueryAndRawQuery)(nil), // 5: Reranker.QuerySource.ConcatQueryAndRawQuery
}
var file_search_config_proto_depIdxs = []int32{
	1, // 0: SearchConfig.reranker:type_name -> Reranker
	2, // 1: Reranker.query_source:type_name -> Reranker.QuerySource
	4, // 2: Reranker.QuerySource.raw_query:type_name -> Reranker.QuerySource.RawQuery
	3, // 3: Reranker.QuerySource.query:type_name -> Reranker.QuerySource.Query
	5, // 4: Reranker.QuerySource.concat_query_and_raw_query:type_name -> Reranker.QuerySource.ConcatQueryAndRawQuery
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_search_config_proto_init() }
func file_search_config_proto_init() {
	if File_search_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_search_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_config_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Reranker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_config_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Reranker_QuerySource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_config_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Reranker_QuerySource_Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_config_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Reranker_QuerySource_RawQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_config_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Reranker_QuerySource_ConcatQueryAndRawQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_search_config_proto_msgTypes[2].OneofWrappers = []any{
		(*Reranker_QuerySource_RawQuery_)(nil),
		(*Reranker_QuerySource_Query_)(nil),
		(*Reranker_QuerySource_ConcatQueryAndRawQuery_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_config_proto_goTypes,
		DependencyIndexes: file_search_config_proto_depIdxs,
		MessageInfos:      file_search_config_proto_msgTypes,
	}.Build()
	File_search_config_proto = out.File
	file_search_config_proto_rawDesc = nil
	file_search_config_proto_goTypes = nil
	file_search_config_proto_depIdxs = nil
}
