# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search_config.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'search_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13search_config.proto\x1a\x17validate/validate.proto\"\x93\x01\n\x0cSearchConfig\x12?\n\rsearcher_type\x18\x03 \x01(\tB\x1a\xfa\x42\x17r\x15R\x07\x63olbertR\nopensearchR\x0csearcherType\x12%\n\x08reranker\x18\x04 \x01(\x0b\x32\t.RerankerR\x08reranker\x12\x1b\n\tuse_group\x18\x05 \x01(\x08R\x08useGroup\"\x97\x04\n\x08Reranker\x12%\n\x0epassage_fields\x18\x02 \x03(\tR\rpassageFields\x12.\n\rreranker_type\x18\x03 \x01(\tB\t\xfa\x42\x06r\x04R\x02\x65\x35R\x0crerankerType\x12\x38\n\x0cquery_source\x18\x04 \x01(\x0b\x32\x15.Reranker.QuerySourceR\x0bquerySource\x12\x1f\n\x0b\x64\x65\x64up_field\x18\x05 \x01(\tR\ndedupField\x1a\xd2\x02\n\x0bQuerySource\x12=\n\traw_query\x18\x01 \x01(\x0b\x32\x1e.Reranker.QuerySource.RawQueryH\x00R\x08rawQuery\x12\x33\n\x05query\x18\x02 \x01(\x0b\x32\x1b.Reranker.QuerySource.QueryH\x00R\x05query\x12j\n\x1a\x63oncat_query_and_raw_query\x18\x03 \x01(\x0b\x32,.Reranker.QuerySource.ConcatQueryAndRawQueryH\x00R\x16\x63oncatQueryAndRawQuery\x1a\x1d\n\x05Query\x12\x14\n\x05\x66ield\x18\x01 \x01(\tR\x05\x66ield\x1a\n\n\x08RawQuery\x1a.\n\x16\x43oncatQueryAndRawQuery\x12\x14\n\x05\x66ield\x18\x01 \x01(\tR\x05\x66ieldB\x08\n\x06sourceJ\x04\x08\x01\x10\x02\x42+B\x11SearchConfigProtoP\x01Z\x14\x62igkinds.or.kr/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\021SearchConfigProtoP\001Z\024bigkinds.or.kr/proto'
  _globals['_SEARCHCONFIG'].fields_by_name['searcher_type']._loaded_options = None
  _globals['_SEARCHCONFIG'].fields_by_name['searcher_type']._serialized_options = b'\372B\027r\025R\007colbertR\nopensearch'
  _globals['_RERANKER'].fields_by_name['reranker_type']._loaded_options = None
  _globals['_RERANKER'].fields_by_name['reranker_type']._serialized_options = b'\372B\006r\004R\002e5'
  _globals['_SEARCHCONFIG']._serialized_start=49
  _globals['_SEARCHCONFIG']._serialized_end=196
  _globals['_RERANKER']._serialized_start=199
  _globals['_RERANKER']._serialized_end=734
  _globals['_RERANKER_QUERYSOURCE']._serialized_start=390
  _globals['_RERANKER_QUERYSOURCE']._serialized_end=728
  _globals['_RERANKER_QUERYSOURCE_QUERY']._serialized_start=629
  _globals['_RERANKER_QUERYSOURCE_QUERY']._serialized_end=658
  _globals['_RERANKER_QUERYSOURCE_RAWQUERY']._serialized_start=660
  _globals['_RERANKER_QUERYSOURCE_RAWQUERY']._serialized_end=670
  _globals['_RERANKER_QUERYSOURCE_CONCATQUERYANDRAWQUERY']._serialized_start=672
  _globals['_RERANKER_QUERYSOURCE_CONCATQUERYANDRAWQUERY']._serialized_end=718
# @@protoc_insertion_point(module_scope)
