# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_pb2 as item__pb2
import search_config_pb2 as search__config__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x1a\nitem.proto\x1a\x13search_config.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1b\x62uf/validate/validate.proto\"\xb9\x02\n\rSearchRequest\x12/\n\x05query\x18\x01 \x03(\x0b\x32\x19.SearchRequest.QueryEntryR\x05query\x12\x18\n\x07\x65xclude\x18\x02 \x01(\tR\x07\x65xclude\x12\x12\n\x04size\x18\x03 \x01(\x05R\x04size\x12/\n\x06\x66ilter\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x66ilter\x12\x1b\n\traw_query\x18\x05 \x01(\tR\x08rawQuery\x12\x0e\n\x02id\x18\x06 \x01(\tR\x02id\x12\x31\n\x07\x66ilters\x18\x07 \x03(\x0b\x32\x17.google.protobuf.StructR\x07\x66ilters\x1a\x38\n\nQueryEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"-\n\x0eSearchResponse\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x05.ItemR\x05items\"\xf4\x01\n\x0eMSearchRequest\x12*\n\x08requests\x18\x01 \x03(\x0b\x32\x0e.SearchRequestR\x08requests\x12\x12\n\x04size\x18\x02 \x01(\x05R\x04size\x12\x1b\n\traw_query\x18\x03 \x01(\tR\x08rawQuery\x12\x37\n\taggregate\x18\x04 \x01(\x0b\x32\x19.MSearchRequest.AggregateR\taggregate\x1aL\n\tAggregate\x12\x16\n\x06method\x18\x01 \x01(\tR\x06method\x12\'\n\x0fpreserve_source\x18\x02 \x01(\x08R\x0epreserveSource\"/\n\x0fMSearchResponse\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\x06.ItemsR\x05items2\x91\x01\n\rSearchService\x12=\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\"\x07/search:\x01*\x12\x41\n\x07MSearch\x12\x0f.MSearchRequest\x1a\x10.MSearchResponse\"\x13\x82\xd3\xe4\x93\x02\r\"\x08/msearch:\x01*B%B\x0bSearchProtoP\x01Z\x14\x62igkinds.or.kr/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013SearchProtoP\001Z\024bigkinds.or.kr/proto'
  _globals['_SEARCHREQUEST_QUERYENTRY']._loaded_options = None
  _globals['_SEARCHREQUEST_QUERYENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHSERVICE'].methods_by_name['Search']._loaded_options = None
  _globals['_SEARCHSERVICE'].methods_by_name['Search']._serialized_options = b'\202\323\344\223\002\014\"\007/search:\001*'
  _globals['_SEARCHSERVICE'].methods_by_name['MSearch']._loaded_options = None
  _globals['_SEARCHSERVICE'].methods_by_name['MSearch']._serialized_options = b'\202\323\344\223\002\r\"\010/msearch:\001*'
  _globals['_SEARCHREQUEST']._serialized_start=139
  _globals['_SEARCHREQUEST']._serialized_end=452
  _globals['_SEARCHREQUEST_QUERYENTRY']._serialized_start=396
  _globals['_SEARCHREQUEST_QUERYENTRY']._serialized_end=452
  _globals['_SEARCHRESPONSE']._serialized_start=454
  _globals['_SEARCHRESPONSE']._serialized_end=499
  _globals['_MSEARCHREQUEST']._serialized_start=502
  _globals['_MSEARCHREQUEST']._serialized_end=746
  _globals['_MSEARCHREQUEST_AGGREGATE']._serialized_start=670
  _globals['_MSEARCHREQUEST_AGGREGATE']._serialized_end=746
  _globals['_MSEARCHRESPONSE']._serialized_start=748
  _globals['_MSEARCHRESPONSE']._serialized_end=795
  _globals['_SEARCHSERVICE']._serialized_start=798
  _globals['_SEARCHSERVICE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
